# event data structure

event = {
    "Report": {
        "AssessmentDate": "12/25/2020",
        "AssessmentNumber": "9a482f6b-90de-4202-a2ab-aed6c91326a4",
        "PhilosophyScores": {
            "Liberal": 49,
            "Behaviorist": 61,
            "Progressive": 60,
            "Humanistic": 62,
            "Radical": 69,
            "Total": 301
        },
        "GroupScores": {
            "GroupA": 28,
            "GroupC": 26,
            "GroupD": 28,
            "GroupF": 33,
            "GroupH": 30,
            "GroupV": 18,
            "GroupW": 35,
            "GroupX": 32,
            "GroupY": 29,
            "GroupZ": 39
        },
        "ScoreEquation": "<p>a + v = 28 + 18 = 49 (Liberal Arts Adult Education)</br><p>d + x = 28 + 32 = 60 (Progressive Adult Education)</br><p>f + y = 33 + 29 = 62 (Humanistic Adult Education)</br><p>h + z = 30 + 39 = 69 (Radical Adult Education)</br><p>c + w = 26 + 35 = 61 (Behaviorist Adult Education)</br>",
        "InventoryMatrix": "\n<tr><td align='center' width='20%'>Inventory Question</td><td align='center'>a</td><td align='center'>v</td><td align='center'>c</td><td align='center'>w</td><td align='center'>d</td><td align='center'>x</td><td align='center'>f</td><td align='center'>y</td><td align='center'>h</td><td align='center'>z</td></tr>\n<tr><td align='center'>1</td><td align='center'>3</td><td bgcolor='#000'> </td><td align='center'>2</td><td bgcolor='#000'> </td><td align='center'>1</td><td bgcolor='#000'> </td><td align='center'>4</td><td bgcolor='#000'> </td><td align='center'>1</td><td bgcolor='#000'> </td></tr>\n<tr><td align='center'>2</td><td bgcolor='#000'> </td><td align='center'>1</td><td bgcolor='#000'> </td><td align='center'>6</td><td bgcolor='#000'> </td><td align='center'>5</td><td bgcolor='#000'> </td><td align='center'>2</td><td bgcolor='#000'> </td><td align='center'>7</td></tr>\n<tr><td align='center'>3</td><td align='center'>2</td><td bgcolor='#000'> </td><td align='center'>2</td><td bgcolor='#000'> </td><td align='center'>5</td><td bgcolor='#000'> </td><td align='center'>4</td><td bgcolor='#000'> </td><td align='center'>3</td><td bgcolor='#000'> </td></tr>\n<tr><td align='center'>4</td><td bgcolor='#000'> </td><td align='center'>2</td><td bgcolor='#000'> </td><td align='center'>1</td><td bgcolor='#000'> </td><td align='center'>6</td><td bgcolor='#000'> </td><td align='center'>7</td><td bgcolor='#000'> </td><td align='center'>7</td></tr>\n<tr><td align='center'>5</td><td align='center'>4</td><td bgcolor='#000'> </td><td align='center'>3</td><td bgcolor='#000'> </td><td align='center'>4</td><td bgcolor='#000'> </td><td align='center'>6</td><td bgcolor='#000'> </td><td align='center'>5</td><td bgcolor='#000'> </td></tr>\n<tr><td align='center'>6</td><td bgcolor='#000'> </td><td align='center'>6</td><td bgcolor='#000'> </td><td align='center'>5</td><td bgcolor='#000'> </td><td align='center'>3</td><td bgcolor='#000'> </td><td align='center'>7</td><td bgcolor='#000'> </td><td align='center'>2</td></tr>\n<tr><td align='center'>7</td><td align='center'>3</td><td bgcolor='#000'> </td><td align='center'>1</td><td bgcolor='#000'> </td><td align='center'>2</td><td bgcolor='#000'> </td><td align='center'>1</td><td bgcolor='#000'> </td><td align='center'>4</td><td bgcolor='#000'> </td></tr>\n<tr><td align='center'>8</td><td bgcolor='#000'> </td><td align='center'>1</td><td bgcolor='#000'> </td><td align='center'>7</td><td bgcolor='#000'> </td><td align='center'>5</td><td bgcolor='#000'> </td><td align='center'>2</td><td bgcolor='#000'> </td><td align='center'>6</td></tr>\n<tr><td align='center'>9</td><td align='center'>7</td><td bgcolor='#000'> </td><td align='center'>6</td><td bgcolor='#000'> </td><td align='center'>4</td><td bgcolor='#000'> </td><td align='center'>5</td><td bgcolor='#000'> </td><td align='center'>3</td><td bgcolor='#000'> </td></tr>\n<tr><td align='center'>10</td><td bgcolor='#000'> </td><td align='center'>3</td><td bgcolor='#000'> </td><td align='center'>6</td><td bgcolor='#000'> </td><td align='center'>7</td><td bgcolor='#000'> </td><td align='center'>5</td><td bgcolor='#000'> </td><td align='center'>4</td></tr>'\n<tr><td align='center'>11</td><td align='center'>1</td><td bgcolor='#000'> </td><td align='center'>1</td><td bgcolor='#000'> </td><td align='center'>1</td><td bgcolor='#000'> </td><td align='center'>2</td><td bgcolor='#000'> </td><td align='center'>2</td><td bgcolor='#000'> </td></tr>\n<tr><td align='center'>12</td><td bgcolor='#000'> </td><td align='center'>3</td><td bgcolor='#000'> </td><td align='center'>7</td><td bgcolor='#000'> </td><td align='center'>5</td><td bgcolor='#000'> </td><td align='center'>4</td><td bgcolor='#000'> </td><td align='center'>6</td></tr>\n<tr><td align='center'>13</td><td align='center'>5</td><td bgcolor='#000'> </td><td align='center'>7</td><td bgcolor='#000'> </td><td align='center'>4</td><td bgcolor='#000'> </td><td align='center'>6</td><td bgcolor='#000'> </td><td align='center'>6</td><td bgcolor='#000'> </td></tr>\n<tr><td align='center'>14</td><td bgcolor='#000'> </td><td align='center'>2</td><td bgcolor='#000'> </td><td align='center'>3</td><td bgcolor='#000'> </td><td align='center'>1</td><td bgcolor='#000'> </td><td align='center'>2</td><td bgcolor='#000'> </td><td align='center'>7</td></tr>\n<tr><td align='center'>15</td><td align='center'>3</td><td bgcolor='#000'> </td><td align='center'>4</td><td bgcolor='#000'> </td><td align='center'>7</td><td bgcolor='#000'> </td><td align='center'>5</td><td bgcolor='#000'> </td><td align='center'>6</td><td bgcolor='#000'> </td></tr>\n<tr><td align='center'>Totals</td><td>28</td><td align='center'>18</td><td>26</td><td align='center'>35</td><td>28</td><td align='center'>32</td><td>33</td><td align='center'>29</td><td>30</td><td align='center'>39</td></tr>\n"
    },
    "Version": "2",
    "User": {
        "Name": "my name",
        "Email": "chris.hare@icloud.com",
        "Gender": "male",
        "BirthYear": "1962",
        "School": "N",
        "Institution": "None",
        "Previous": "Yes",
        "Country": "United States"
    },
    "Inventory": {
        "q1a": "1",
        "q1b": "2",
        "q1c": "3",
        "q1d": "1",
        "q1e": "4",
        "q2a": "5",
        "q2b": "6",
        "q2c": "7",
        "q2d": "2",
        "q2e": "1",
        "q3a": "4",
        "q3b": "3",
        "q3c": "2",
        "q3d": "5",
        "q3e": "2",
        "q4a": "6",
        "q4b": "7",
        "q4c": "1",
        "q4d": "7",
        "q4e": "2",
        "q5a": "6",
        "q5b": "3",
        "q5c": "5",
        "q5d": "4",
        "q5e": "4",
        "q6a": "5",
        "q6b": "3",
        "q6c": "6",
        "q6d": "2",
        "q6e": "7",
        "q7a": "1",
        "q7b": "1",
        "q7c": "2",
        "q7d": "3",
        "q7e": "4",
        "q8a": "5",
        "q8b": "6",
        "q8c": "7",
        "q8d": "1",
        "q8e": "2",
        "q9a": "3",
        "q9b": "4",
        "q9c": "5",
        "q9d": "6",
        "q9e": "7",
        "q10a": "7",
        "q10b": "6",
        "q10c": "5",
        "q10d": "4",
        "q10e": "3",
        "q11a": "2",
        "q11b": "1",
        "q11c": "1",
        "q11d": "1",
        "q11e": "2",
        "q12a": "3",
        "q12b": "4",
        "q12c": "5",
        "q12d": "6",
        "q12e": "7",
        "q13a": "6",
        "q13b": "7",
        "q13c": "6",
        "q13d": "5",
        "q13e": "4",
        "q14a": "3",
        "q14b": "2",
        "q14c": "1",
        "q14d": "7",
        "q14e": "2",
        "q15a": "3",
        "q15b": "4",
        "q15c": "5",
        "q15d": "6",
        "q15e": "7"
    },
    "statusCode": 200,

    "numberStatusCode": 200,
    "dateStatusCode": 200,
    "scoresStatusCode": 200
}
